name: watchlist
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  common:
    path: ../../shared/common
  components:
    path: ../../shared/components
  core:
    path: ../../shared/core
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  movies:
    path: ../../features/movies
  tv_series:
    path: ../../features/tv_series

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
