name: ditonton

packages:
  - ./
  - features/**
  - shared/**

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages
  build_runner:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run `flutter analyze` in all packages

  inspect_format:
    run: melos exec -- "dart format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages
  format:
    run: melos exec -- "dart format . "
    description: Run `flutter format .` in all packages
  test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
