name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.0
  get_it: ^7.1.3
  google_fonts: ^4.0.4
  http: ^0.13.3
  path_provider: ^2.0.2
  provider: ^6.0.3
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
